
version: "3.9"
services:
  app:
    build: .
    container_name: oauth-manager-demo-app
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/usr/src/app
    command: sh -c "npm install && npm run start"
  db:
    image: postgres:15
    container_name: oauth-manager-demo-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oauth_demo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: oauth-manager-demo-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
  adminer:
    image: adminer:4
    container_name: oauth-manager-demo-adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  pgdata:
  redisdata:
